# Generated by Django 5.2.3 on 2025-06-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='phone_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
