# Generated by Django 5.2.3 on 2025-06-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsign', '0002_alter_sign_email_alter_sign_name_alter_sign_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='phone_no',
            field=models.PositiveIntegerField(),
        ),
    ]
