# Generated by Django 5.2.3 on 2025-06-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsign', '0003_alter_sign_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
