# Generated by Django 5.2.3 on 2025-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsign', '0004_alter_sign_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='name',
            field=models.CharField(),
        ),
    ]
