# Generated by Django 5.2.3 on 2025-06-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField()),
                ('route_no', models.CharField()),
                ('bus_start_loc', models.CharField()),
                ('bus_end_loc', models.CharField()),
                ('service_start_time', models.TimeField()),
                ('service_reached_time', models.TimeField()),
                ('count_of_seats', models.IntegerField()),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField()),
                ('drop', models.CharField()),
                ('seat', models.IntegerField()),
                ('date', models.DateField()),
                ('first_passanger', models.CharField()),
                ('second_passanger', models.CharField(null=True)),
                ('third_passanger', models.CharField(null=True)),
            ],
        ),
    ]
