# Generated by Django 5.2.3 on 2025-06-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_journey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='journey',
        ),
    ]
