# Generated by Django 5.2.3 on 2025-06-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField()),
                ('drop', models.CharField()),
                ('seat', models.IntegerField()),
                ('date', models.DateField()),
                ('passanger_name', models.CharField()),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField()),
                ('ticket_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.buslist')),
            ],
        ),
    ]
